In [79]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
%matplotlib inline

Q1. Pandas version -

What's the version of Pandas that you installed?

In [80]:
pd.__version__

'2.3.1'

Answer '2.3.1'

In [81]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-10-01 01:38:56--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv


Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.01s   

2025-10-01 01:38:56 (55.6 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [82]:
df= pd.read_csv("car_fuel_efficiency.csv")

In [83]:
len(df)

9704

Q3. Fuel types

How many fuel types are presented in the dataset?

In [84]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

2 fuel types are present in the dataset

Q4. Missing values

How many columns in the dataset have missing values?

In [85]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Answer: 4 columns in the dataset have missing values

Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [86]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

Answer: 23.75

Q6. Median value of horsepower

Find the median value of horsepower column in the dataset.

Next, calculate the most frequent value of the same horsepower column.

Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

Now, calculate the median value of horsepower once again.

In [87]:
df['horsepower'].median()

np.float64(149.0)

In [88]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [89]:
df.horsepower.fillna(0)

0       159.0
1        97.0
2        78.0
3         0.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [90]:
df.horsepower.median()

np.float64(149.0)

Answer: No change

Q7. Sum of weights

Select all the cars from Asia

Select only columns vehicle_weight and model_year

Select the first 7 values

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [91]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [92]:
df[df['origin']=='Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [93]:
asia_cars = df.loc[df['origin']=='Asia',['vehicle_weight','model_year']].head(7)

In [94]:
X = asia_cars.to_numpy()

In [95]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [96]:
XT= X.T

In [97]:
XTX = np.dot(XT,X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [98]:
XTX_inv = np.linalg.pinv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [99]:
Z= np.dot(XTX_inv,XT)
Z

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [100]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [101]:
w= np.dot(Z,y)
w


array([0.01386421, 0.5049067 ])

In [102]:
np.sum(w)

np.float64(0.5187709081074039)

Answer: 0.519